# Power menu
[[apps.custom]]
name = "Logout"
exec = "hyprctl dispatch exit"
icon = "system-log-out"
keywords = ["exit"]

[[apps.custom]]
name = "Shutdown"
exec = "systemctl poweroff"
icon = "system-shutdown"
keywords = ["poweroff", "shutdown"]

[[apps.custom]]
name = "Reboot"
exec = "systemctl reboot"
icon = "system-reboot"
keywords = ["restart", "reboot"]

# General
[general]
max_results = 5       # Max results when searching
initial_results = 5   # Results shown before typing (0 = just search bar)

[apps]
exclude = ["Avahi SSH Server Browser", "Avahi VNC Server Browser", "Avahi Zeroconf Browser", "CMake", "btop++"]

# Custom app entries
[[apps.custom]]
name = "Pogostuck Split Tracker"
exec = "/home/doccia/workspace/github/pogostuck-split-tracker/dist/pogostuck-split-tracker-1.1.1.AppImage"
icon = "input-gaming"
keywords = ["pogosplit", "split"]
